### ISSUE TITLE
Consider a Transparency/Opaque Option

### ISSUE THREAD

**Issue by cvweiss** [unreadablewxy/eveol#2]
![image](https://user-images.githubusercontent.com/739285/137757672-52b9f214-868c-4488-9c78-5d3bdf686bba.png)

Reading the system name, as well as seeing some of the options, can be difficult when this pane does not have focus and the map is displaying behind the pane. Please consider adding an option that all panes can be set fully opaque regardless of having focus/mouseover or not.

**Comment by unreadablewxy** [comment]
Fixed in 0.3.0
